# production Infrastructure Configuration
# Generated by Pulse Infrastructure Discovery

terraform {
  required_version = ">= 1.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = local.common_tags
  }
}

locals {
  project_name = "production"
  environment  = var.environment

  common_tags = {
    Project     = local.project_name
    Environment = local.environment
    ManagedBy   = "Terraform"
    CreatedBy   = "Pulse-Discovery"
  }

}

# Direct Resource Blocks for Import
# Data sources
data "aws_availability_zones" "available" {
  state = "available"
}

